module.exports = {
  REQUEST_CONTENT: 'REQUEST_CONTENT',
  RECEIVE_CONTENT: 'RECEIVE_CONTENT',
  UPDATE_CONTENT: 'UPDATE_CONTENT',
  DELETE_CONTENT: 'DELETE_CONTENT',
  INVALIDATE_CONTENT: 'INVALIDATE_CONTENT',
  DISPLAY_MESSAGE: 'DISPLAY_MESSAGE'
}