export { default as Bar } from 'presentations/icons/Bar'
export { default as Delete } from 'presentations/icons/Delete'
export { default as Edit } from 'presentations/icons/Edit'
export { default as GridViewIcon } from 'presentations/icons/GridViewIcon'
export { default as Image } from 'presentations/icons/Image'
export { default as Line } from 'presentations/icons/Line'
export { default as ListViewIcon } from 'presentations/icons/ListViewIcon'
export { default as Logo } from 'presentations/icons/Logo'
export { default as LogoTextIcon } from 'presentations/icons/LogoTextIcon'
export { default as MoreVertIcon } from 'presentations/icons/MoreVertIcon'
export { default as Note } from 'presentations/icons/Note'
export { default as Pie } from 'presentations/icons/Pie'
export { default as Treemap } from 'presentations/icons/Treemap'

