module.exports = {
  REQUEST_DASHBOARDS: 'REQUEST_DASHBOARDS',
  RECEIVE_DASHBOARDS: 'RECEIVE_DASHBOARDS',
  UPDATE_DASHBOARD: 'UPDATE_DASHBOARD',
  DELETE_DASHBOARD: 'DELETE_DASHBOARD',
  DISPLAY_MESSAGE: 'DISPLAY_MESSAGE',
  FILTER: 'FILTER'
}